### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by kadirsahbaz** [oreillymedia/creating_apps_in_kivy#1]
The book indicates "no need", but OpenWeatherMap needs an API key from now on.

**Comment by talaniz** [comment]
Not sure if this will be fixed sometime soon, but it's fairly simple to fix. Just sign up for the free API key at OpenWeatherMap. Then add the following to the beginning of `main.py`:

`API_KEY =  '123thisisanapikey456`

from there it's just a matter of concatenating it onto the end of the `search_template` variable:

```
`def search_location(self):
        search_template = "http://api.openweathermap.org/data/2.5/" + \
                          "find?q={}&type=like" + "&APPID=" + API_KEY
        search_url = search_template.format(self.search_input.text)
        request = UrlRequest(search_url, self.found_location)`
```

I've tested and have it working as expected.
